### ISSUE TITLE
Clothing replaced by same clothing

### ISSUE THREAD

**Issue by john-backlot** [miccunifi/ladi-vton#11]
We're running inference to recreate paper results using the VITON-HD dataset (_test_pairs.txt_ in our conda environment), however the results appear to be slightly modified versions of the original clothing. It appears as if it's going through a diffusion pass, but not applying the clothing.

Running on a Windows 11 4090 PC, following the default settings/commands provided.

Images:
![original_image](https://github.com/miccunifi/ladi-vton/assets/79934252/f2e10d04-a2fb-4734-a2b3-54372415e735)
![clothing](https://github.com/miccunifi/ladi-vton/assets/79934252/f1877e6d-7d57-446c-9512-5d542d41a905)
![final_image](https://github.com/miccunifi/ladi-vton/assets/79934252/098a5b9e-aefa-47ea-893d-869f97f78d81)

**Comment by Heimdall-Nss** [comment]
> Hi [@john-backlot](https://github.com/john-backlot) Thanks for your interest in our work!!
> 
> It appears that the code is running in the 'paired' setting, where the in-shop garment matches the one worn by the model. Consequently, the resulting image closely resembles the input image.
> 
> To obtain the desired results, I recommend running the inference with the flag **--test_order unpaired**. In this setting, the in-shop garment differs from what the model is wearing. By using this flag, you should be able to achieve the expected outcomes.
> 
> Alberto

My inference setup is as follows:
accelerate launch --mixed_precision="fp16" --num_processes=4 src/inference.py \
--dataset vitonhd \
--dresscode_dataroot /data/xx/DressCode \
--vitonhd_dataroot /data/xx/VITON-HD \
--output_dir res/viton \
--test_order unpaired \
--mixed_precision fp16 \
--use_png \
--enable_xformers_memory_efficient_attention

Why does the result look like 【paired】 mode?
I have confirmed that the loaded txt file is unpaired

Can anyone help me with this, I'm very confused

**Comment by Heimdall-Nss** [comment]
I visualized the input model and warp image, and they look fine.This is very strange！..

![Image](https://github.com/user-attachments/assets/ffe479af-fdca-4503-8c1a-f4e11b2b373c)

![Image](https://github.com/user-attachments/assets/5d3e3bf6-23b0-49e7-ab92-358b920e64f8)
