### ISSUE TITLE
Poor result on kid score

### ISSUE THREAD

**Issue by Lipurple** [miccunifi/ladi-vton#13]
Hey, great project!
I want to replicate the results of paired dataset, other metric score is same as shown in the paper, but the kid score is very smaller than that shown in paper:
![53fb4ab9-75da-459f-be72-d7232739b3cd](https://github.com/miccunifi/ladi-vton/assets/49636115/305f5880-1fec-4e42-b9ee-a50cb90380b7)

Could you possibly assist or provide any guidance to address this issue? Thanks in advance.

**Comment by ABaldrati** [comment]
Hi @Lipurple 
Thanks for your interest in our work!

Following previous works, we report the kid metric multiplied by a factor of 10^3 in our paper.

I hope this solves your issue,
Alberto

**Comment by Lipurple** [comment]
I see, thank you very much!

**Comment by shaoke317** [comment]
![Uploading 屏幕截图 2024-10-25 202802.png…]()
![380175431-4fe44ea6-3434-4733-8461-bfa191a63560](https://github.com/user-attachments/assets/83d60223-18da-4534-9e98-56cf6
![380176686-e3c51f97-e91e-416b-9639-130ea4446595](https://github.com/user-attachments/assets/51576f3a-4a98-4377-98ac-95997664b3f4)
d1b058e)


你好，我在推理的过程中遇到了CLIP模型权重的问题，推理代码可以运行，生成生成推理后的图片。请问你遇到了这样的问题吗？
其次，我还想请教一下你是怎么在vitonhd数据集上面计算指标的，我的指标和论文中的指标完全不同，我运行指标代码的命令是python src/utils/val_metrics.py --gen_folder output/unpaired --dataset vitonhd --vitonhd_dataroot asset/data/VITON-HD --test_order unpaired --category upper_body，请问这个指标不正常的结果会与CLIP模型有关吗？
