### ISSUE TITLE
Not realistic

### ISSUE THREAD

**Issue by Emadeon** [miccunifi/ladi-vton#14]
Hi, so I tried using this model but the result generated is not realistic. Do you know why this can be. The upper body shirt on this is tried on using the model. It is this shirt.
<img width="331" alt="image" src="https://github.com/miccunifi/ladi-vton/assets/86068953/f07a51da-34cf-4dca-80cd-2f165e090b84">

<img width="225" alt="image" src="https://github.com/miccunifi/ladi-vton/assets/86068953/c52ec25f-f905-4ed7-a417-f930e2881a5b">

**Comment by Emadeon** [comment]
Here is another example. This is not the shirt it is showing me.
<img width="234" alt="image" src="https://github.com/miccunifi/ladi-vton/assets/86068953/caf31386-cd9c-4e57-9c48-44ee34bb3099">
<img width="209" alt="image" src="https://github.com/miccunifi/ladi-vton/assets/86068953/4ffbaaec-f9dc-4d9d-9477-64deb877f990">

**Comment by omedivad** [comment]
@Emadeon,

Our code is not supposed to work with custom examples. 
We cannot know how you adapted it. 

Also, to make it work on those examples, you must have extracted information (such as pose, label map, etc.), and we do not know how you did that.

It is difficult to say why it doesn't work.

**Comment by Emadeon** [comment]
Alright thank you.
