### ISSUE TITLE
Can handle lower body garments？

### ISSUE THREAD

**Issue by all1new** [miccunifi/ladi-vton#16]
Can I try on the pants, please, and if so, how can I do it?

**Comment by ABaldrati** [comment]
Hi @all1new,

Yes, the system described in the paper can handle lower-body garments. If you're interested in evaluating the performance of ladi-vton specifically for lower-body garments, I recommend running experiments using the DressCode dataset. Please note that Viton-HD, on the other hand, focuses exclusively on upper body garments.

Best regards,
Alberto

**Comment by all1new** [comment]
hello! Can you send me the dresscode dataset? My email address is caizhenhuang630@163.com

**Comment by Jdachang** [comment]
> 你好@all1new,
> 
> 是的，论文中描述的系统可以处理下半身的衣服。如果您有兴趣评估 ladi-vton 专门针对下半身服装的性能，我建议您使用 DressCode 数据集运行实验。请注意，另外，Viton-HD 只于逻辑上半身服装。
> 
> 最好的问候， 阿尔贝托

你好,可以把DressCode发我一份吗?

**Comment by Jdachang** [comment]
> Hi @all1new,
> 
> Yes, the system described in the paper can handle lower-body garments. If you're interested in evaluating the performance of ladi-vton specifically for lower-body garments, I recommend running experiments using the DressCode dataset. Please note that Viton-HD, on the other hand, focuses exclusively on upper body garments.
> 
> Best regards, Alberto

Run the code according to the project, and finally only get some calculation indicators. How do you deal with the clothes and dresses on the lower body?
We are expecting a reply.

**Comment by ABaldrati** [comment]
> hello! Can you send me the dresscode dataset? My email address is [caizhenhuang630@163.com](mailto:caizhenhuang630@163.com)

To download the Dress Code dataset you need to follow the instruction in the official repo https://github.com/aimagelab/dress-code
