### ISSUE TITLE
Time and hardware for inference and training

### ISSUE THREAD

**Issue by joackobengochea** [miccunifi/ladi-vton#2]
Hi! Congrats on the excellent paper!

Could you tell me how much time it takes to run an inference and on which hardware?

Also, with which hardware did you train and for how long? 

Thanks!!

**Comment by ABaldrati** [comment]
Hi @joackobengochea 
Thanks for your interest in our work!

We train our models on a single NVIDIA A100, which takes about three days.
The inference time speed is roughly the same as Stable Diffusion and depends on how many denoising steps you decide to perform. On the same hardware, when using 50 denoising steps, performing batched inference takes about one second per image.

Hope this answers the question,
Alberto
