### ISSUE TITLE
Outdated arguments in function

### ISSUE THREAD

**Issue by mgp123** [miccunifi/ladi-vton#23]
The Encoder uses the `get_down_block ` [here](https://github.com/miccunifi/ladi-vton/blob/dea53937ab54588848a2d7132574a99ec8daed92/src/models/vae.py#L65C33-L65C33) using parameter `attn_num_head_channels` but `get_down_block ` doesn't have such parameter in newer versions of the `diffusers` library

**Comment by ABaldrati** [comment]
Hi @mgp123 

As pointed out in the [README](https://github.com/miccunifi/ladi-vton#getting-started) our code is supposed to work with version 0.14 of diffusers.

Alberto
