### ISSUE TITLE
questions about the KID metric

### ISSUE THREAD

**Issue by Ganzhi-e** [miccunifi/ladi-vton#28]
Hi,thank you for your great work!

After inferencing on VITON-HD dataset with your released model, I got KID_p 0.0015 (1.08 in your paper), and KID_u 0.0018 (1.60 in your paper). Why such a big difference？ 

Thanks for any advices.

**Comment by ABaldrati** [comment]
Hi @Ganzhi-e 
Thanks for your interest in our work!

As stated in #13, following previous works, we report the kid metric multiplied by a factor of 10^3 in our paper.

I hope this solves your issue,
Alberto

**Comment by Ganzhi-e** [comment]
Thank you very much !

**Comment by shaoke317** [comment]
![屏幕截图 2024-10-25 202802](https://github.com/user-attachments/assets/0a4f61e9-5b3e-453c-83fb-d7da68e6fcd9)
![380176686-e3c51f97-e91e-416b-9639-130ea4446595](https://github.com/user-attachments/assets/c898d684-20f6-4036-818b-dbbd1cb1ee73)

你好，我在推理的过程中遇到了CLIP模型权重的问题，但是推理代码可以跑通，也会生成推理后的图片。请问你有遇到这样的问题吗？
其次，我还想请教一下你是怎么在vitonhd数据集上面计算指标的，我的指标与论文中的指标完全不同，我运行指标代码的命令是python src/utils/val_metrics.py --gen_folder output/unpaired --dataset vitonhd --vitonhd_dataroot assets/data/VITON-HD --test_order unpaired --category upper_body，请问这个指标不正常的结果会与CLIP模型有关吗
![Uploading 屏幕截图 2024-10-25 203149.png…]()
