### ISSUE TITLE
Use lower_body, dresses and all

### ISSUE THREAD

**Issue by Sorokopudov** [miccunifi/ladi-vton#31]
Thanks for your project! how can i use your project for trying on bottoms (pants, skirts) or for dresses? I tested on the VITON-HD dataset, and I got only the top.

**Comment by beppefolder** [comment]
Hi @Sorokopudov !
Thanks for the interest in our work!
VITON-HD only contains upper body clothes. 
 
If you want to try dresses and lower body clothes, please refer to the README section about the download of the Dress Code dataset which contains the clothes categories you are interested in.

**Comment by Sorokopudov** [comment]
@beppefolder Thank you!

**Comment by sudip550** [comment]
> @beppefolder Thank you!



> Hi @Sorokopudov ! Thanks for the interest in our work! VITON-HD only contains upper body clothes.
> 
> If you want to try dresses and lower body clothes, please refer to the README section about the download of the Dress Code dataset which contains the clothes categories you are interested in.

does it work with custom images??

**Comment by giuseppecartella** [comment]
> > @beppefolder Thank you!
> 
> > Hi @Sorokopudov ! Thanks for the interest in our work! VITON-HD only contains upper body clothes.
> > If you want to try dresses and lower body clothes, please refer to the README section about the download of the Dress Code dataset which contains the clothes categories you are interested in.
> 
> does it work with custom images??

Hi @sudip550 ,

You can try the model with your custom images. 
Please note that you need to process your images in a Dress Code-like or VITON-HD-like format.
This means that you need to extract the model body pose of your custom image (we used the openpose model), the segmentation map (we used the SCHP model with 18 classes) and so on...

Giuseppe

**Comment by sudip550** [comment]
> > > @beppefolder Thank you!
> > 
> > 
> > > Hi @Sorokopudov ! Thanks for the interest in our work! VITON-HD only contains upper body clothes.
> > > If you want to try dresses and lower body clothes, please refer to the README section about the download of the Dress Code dataset which contains the clothes categories you are interested in.
> > 
> > 
> > does it work with custom images??
> 
> Hi @sudip550 ,
> 
> You can try the model with your custom images. Please note that you need to process your images in a Dress Code-like or VITON-HD-like format. This means that you need to extract the model body pose of your custom image (we used the openpose model), the segmentation map (we used the SCHP model with 18 classes) and so on...
> 
> Giuseppe

Thank you sir.... I want to use with girl's dresses.. please tell me how to run this...
