### ISSUE TITLE
What should I do to use different Inpaint models?

### ISSUE THREAD

**Issue by kadirnar** [miccunifi/ladi-vton#34]
SD-XL Inpaint:

https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_inpaint.py

Controlnet Inpaint:

https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py

Do I need to train to use this models? Or is it enough for me to develop a new pipe code? What should I do? Can you help me?

**Comment by kadirnar** [comment]
Question-2:

When I test different clothing images, the results are bad. I want to fix this. Can we increase accuracy with Controlnet models?

https://github.com/miccunifi/ladi-vton/issues/14

**Comment by ABaldrati** [comment]
> Do I need to train to use this models? Or is it enough for me to develop a new pipe code? What should I do? Can you help me?

For using a different inpainting model you should retrain all the models from scratch
Alberto
