### ISSUE TITLE
Released checkpoint not found

### ISSUE THREAD

**Issue by Leon-Huang001208** [miccunifi/ladi-vton#55]
URL: https://github.com/miccunifi/ladi-vton/releases/download/weights/ in hubconf.py does not exist, but it is referenced in inference.py, did you release the checkpoints?

**Comment by Leon-Huang001208** [comment]
Nevermind

**Comment by ShroukMansour** [comment]
what updates on this pls?  @Leon-Huang001208

**Comment by shaoke317** [comment]
(https://github.com/miccunifi/ladi-vton/releases)你应该查找这个网址
