### ISSUE TITLE
Not works well in Textual or Letters

### ISSUE THREAD

**Issue by husonchen** [miccunifi/ladi-vton#6]
By running command:
python src/inference.py --dataset vitonhd --vitonhd_dataroot zalando-hd-resized --output_dir output --test_order paired --batch_size 1 --mixed_precision fp16
I found it not works well in textual or letters, like those badcases:
<img width="627" alt="image" src="https://github.com/miccunifi/ladi-vton/assets/10356228/4af5a9d9-6280-4c7c-bcb7-552b2dd939b1">
<img width="384" alt="image" src="https://github.com/miccunifi/ladi-vton/assets/10356228/1986467f-43fa-4616-89db-ecd2c225ab84">
<img width="638" alt="image" src="https://github.com/miccunifi/ladi-vton/assets/10356228/86ac58f6-f8a3-4cbf-b299-39675949aea9">
<img width="379" alt="image" src="https://github.com/miccunifi/ladi-vton/assets/10356228/407fd369-3f46-49d9-a847-472b7ee9d048">
That phenomenon is not mentioned in your paper，is there any way to fix it ?

**Comment by phongnhhn92** [comment]
Hi, I also observe the same issue. This might be the limitation of the current model.

**Comment by ABaldrati** [comment]
Hi @husonchen
Thanks for your interest in our work!

Thank you for bringing up this issue. We have taken note of this limitation in our approach. We argue that the behavior you highlighted results from our model's reliance on Stable Diffusion. Stable Diffusion has limitations, particularly in reproducing readable text or accurately capturing complex high-frequency details.

We believe this limitation could be addressed by using a non-latent diffusion approach. Of course, the "standard" diffusion methods have a higher computational load and require more resources.

Alberto
