### ISSUE TITLE
Real world results

### ISSUE THREAD

**Issue by ParadiseN1** [miccunifi/ladi-vton#7]
Hi, thank you for such a nice work. I was wondering, have you tried your model on real-world data outside of the datasets you mentioned in the paper, both target model and garment?

Also, a question regarding training, have you merged those datasets for training or have you trained separate models for each dataset?

**Comment by ABaldrati** [comment]
Hi @ParadiseN1 
Thanks for your interest in our work!

We did not have time to test our model on real-world data.

We did train one model for each dataset.

Alberto
