### ISSUE TITLE
poor result

### ISSUE THREAD

**Issue by verifie-global** [miccunifi/ladi-vton#8]
I have tested on VitonHD dataset and getting very poor results, see command below:

python3 src/inference.py --dataset vitonhd  --vitonhd_dataroot /content/VITON-HD --output_dir ./ --test_order unpaired --category all --batch_size 8 --mixed_precision fp16  --num_workers 8

![01265_00](https://github.com/miccunifi/ladi-vton/assets/55047804/f01b2b7f-a9c3-43af-b6db-c3211ff95c9a)

![08646_00](https://github.com/miccunifi/ladi-vton/assets/55047804/4997daa7-e584-430d-9eab-094324314082)

![11078_00](https://github.com/miccunifi/ladi-vton/assets/55047804/90787402-a9a1-4e19-bba9-93b99ac3b2cf)

**Comment by ABaldrati** [comment]
Hi @verifie-global

To properly answer the question we need more information about your system and python environment.
We did not observe anything similar during our tests.

Did you use the suggested environment (installation instructions in the README)?
You could also try to use fp32 precision for running the inference.

Alberto

**Comment by ABaldrati** [comment]
Yeah sorry, for running using fp32 you should use the choice 'no'

**Comment by verifie-global** [comment]
I have setup environment as written in README.
conda env create -n ladi-vton -f environment.yml
conda activate ladi-vton

Please help run demo correctly.

**Comment by omedivad** [comment]
Hello, @verifie-global!

Other users can reproduce the demo correctly.
Could you please provide us with more information about your case? 

 Have you modified the code? 
Can you copy-paste the command you use to run the experiment?
Finally, could you give me more info about the hardware you're running this demo on?

Best,

Davide

**Comment by verifie-global** [comment]
I don't modify the code. I just create conda environment. I have download the VITON-HD. change the test_pairs.txt for running the code for image. The content of test_pairs.txt is a 01265_00.jpg 02914_00.jpg
GPU is a Tesla M40
processor Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz
OS is Ubuntu 20.04.4 LTS
command is a

python3 src/inference.py --dataset vitonhd  --vitonhd_dataroot /content/VITON-HD --output_dir ./output/ --test_order unpaired --category upper_body --batch_size 32 --mixed_precision no  --num_workers 8

**Comment by omedivad** [comment]
The problem may be your GPU. 
Are you able to test it on a newer GPU?

We can tell you that the inference works on Nvidia 3090 and A100.

**Comment by verifie-global** [comment]
can I run it with CPU only?
