### ISSUE TITLE
Poor results

### ISSUE THREAD

**Issue by ml1652** [miccunifi/ladi-vton#9]
Hi , I've been attempting to replicate the results you demonstrated in Figure 7 of your paper. However, the outcome is not as presented in your paper. Specifically, the pattern on the T-shirt is not being reproduced. 
![image](https://github.com/miccunifi/ladi-vton/assets/33670846/063310ff-4d18-497b-a824-57b6f624de6a)
Here's the same garment I found in zalando-hd
![00579_00](https://github.com/miccunifi/ladi-vton/assets/33670846/91135340-6bbd-4492-af4c-74d0ac1a8d0d)
Here is the result when I run your code.
![00654_00_00579_00](https://github.com/miccunifi/ladi-vton/assets/33670846/c62ef513-8edb-4a82-8946-6438c9a173e8)
Could you possibly assist or provide any guidance to address this issue? Thanks in advance.

**Comment by ABaldrati** [comment]
Hi @ml1652 

As depicted in the caption the figure you reported (Figure 7) is an ablation study on the Stable Diffusion VAE and EMASC contribution.
The images in the figure are compressed and decompressed using the Stable Diffusion VAE without using the denoising network.

Alberto

**Comment by trituenhantao** [comment]
> Hi @ml1652
> 
> As depicted in the caption the figure you reported (Figure 7) is an ablation study on the Stable Diffusion VAE and EMASC contribution. The images in the figure are compressed and decompressed using the Stable Diffusion VAE without using the denoising network.
> 
> Alberto

Hi @ABaldrati
how to using the denoising network.

**Comment by TalhaUusuf** [comment]
Also from the paper as the mask is inverted (cloth area black , rest white) so the EMASC module learns to reconstruct the area other than cloth (white area) i.e. hands, arms, face so it seems confused to think EMASC will have effect on the cloth pattern rendered. From the paper and pipeline code seemingly warping module has the greatest on cloth patterns.

![image](https://github.com/miccunifi/ladi-vton/assets/129854957/f139bec2-015e-4097-bfbb-30bae8f3ffa4)
